name: 'JSON to environment variables'
author: 'Roberto García'
description: 'This action reads json file and writes its content as environment variables with optional secret masking'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  json-string: 
    description: 'JSON string to parse.'
    required: true
  prefix:
    description: 'The prefix for variables.'
    required: false
    default: 'json'
  masked:
    description: 'Mask variables as secrets.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'index.js'
