name: 'JSON to environment variables'
description: 'Converts JSON string into environment variables'
inputs:
  json-string: 
    description: 'JSON string to parse.'
    required: true
  prefix:
    description: 'Prefix for variables'
    required: false
    default: 'json'
  masked:
    description: 'Mask variables as secrets'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'index.js'
